### ISSUE TITLE
Cache Location of .git Directory

### ISSUE THREAD

**Issue by Kurt-von-Laven** [endlessm/difflint#14]
Currently we call `repo_git` twice, which is most likely a minor performance hit. Repeating the calls rather than caching the initial value opens us up to the possibility that the directory we read from and the directory we write to are not the same.

A.C.
* [ ] We only find the .git directory once.

**Comment by BlackVegetable** [comment]
I'm going to address this by having `repo_root` cache its value via a decorator.

**Comment by BlackVegetable** [comment]
This will be solved when #15 is merged.

**Comment by BlackVegetable** [comment]
Completed.
