### ISSUE TITLE
Breaks committing a merge conflict resolution

### ISSUE THREAD

**Issue by ptomato** [endlessm/difflint#5]
The following sequence of commands should expose a bug:
```sh
mkdir test
cd test
git init
echo 'difflint' > .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
echo 'a' >file.js
git add file.js
git commit -m first
git checkout -b branch
echo 'b' >>file.js
git commit -a -m branch
git checkout master
echo 'c' >>file.js
git commit -a -m second
git merge branch  # merge conflict!
echo 'a' >file.js
echo 'b' >>file.js
echo 'c' >>file.js
git add file.js
git commit
```
Notice that the usual autogenerated merge commit message is missing from the commit message editor. When you type a commit message and close the editor, you get the following error:
```
NOTICE: Check lintdiff.log for linting error details.
fatal: could not open '.git/MERGE_HEAD' for reading: No such file or directory
```
and the commit is aborted. Running `git commit` a second time allows you to commit normally, but still without the autogenerated merge commit message.

My theory is that maybe stashing and unstashing destroys the special "merge commit" status.

**Comment by BlackVegetable** [comment]
I'll take a look into this.  I didn't notice this issue until now; sorry!

**Comment by BlackVegetable** [comment]
This commit on a separate project has the solution (albeit in Ruby) https://github.com/brigade/overcommit/commit/6c5a7b7ab92c6bbe4e1a9d874762b7b50a920593 . I'll see if I can write up something similar in python for this case but I'd like to see if we can get our outstanding PR merged first.

**Comment by BlackVegetable** [comment]
Alright, I'll see if I can get around to this.  I probably won't have much chance to do so for a couple weeks though. :(

**Comment by BlackVegetable** [comment]
Turns out my fix-in-progress for this is dependent on fixing the orphaned branch problem.  I'll tackle that one first.

**Comment by BlackVegetable** [comment]
It is dependent on this because the test that you outlined depends on it.

**Comment by ptomato** [comment]
Really? I didn't create any orphan branches in my test above; or do you mean if you want to test it in an existing repo instead of creating a new one?

**Comment by BlackVegetable** [comment]
Orphan == no prior history for the sake of these bugs.  Regardless, I just barely got this working (on a repo with previous history.  The other problem shouldn't take long though.)  I'll have a PR soon.

**Comment by BlackVegetable** [comment]
Ready for a review.  This introduces the nasty behavior of requiring commits to be run from the root directory of the repo.  If you can think of an elegant way around that, I'd love to hear it.

**Comment by Kurt-von-Laven** [comment]
I guess you could walk up the file tree until you see a .git repo?

**Comment by BlackVegetable** [comment]
Ready for review again.

**Comment by BlackVegetable** [comment]
Up for review again.

**Comment by BlackVegetable** [comment]
I added a commit to clean up the imports.  If either of you could give it a quick look, I'd appreciate it.

**Comment by Kurt-von-Laven** [comment]
**CR Pass**
